---
version: '3.7'
services:
  db:
    image: mysql:5.7
    init: true
    volumes:
      - db:/var/lib/mysql
      - ./docker/db:/etc/mysql/conf.d:ro
    ports:
      - ${DOCKER_HOST_DB_PORT:-3306}:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

volumes:
  db:
    driver: local
