---
version: '3'
services:
  app:
    image: ${APP_IMAGE}
    ports:
      - '0:3000'
    logging:
      driver: awslogs
      options:
        awslogs-group: /rails-structured-logging/production/app/main
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecs
