---
# @see Using ECS parameters - aws/amazon-ecs-cli https://github.com/aws/amazon-ecs-cli#using-ecs-parameters
version: 1
task_definition:
  ecs_network_mode: bridge
  task_role_arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/ecs-test-ecs-task-role
  task_execution_role: ecsTaskExecutionRole
  services:
    app:
      essential: true
      mem_reservation: 512M
      secrets:
        - name: DB_HOST
          value_from: /rails-structured-logging/production/rds/host
        - name: DB_PORT
          value_from: /rails-structured-logging/production/rds/port
        - name: DB_USER
          value_from: /rails-structured-logging/production/rds/user
        - name: DB_PASSWORD
          value_from: /rails-structured-logging/production/rds/password
        - name: REDIS_HOST
          value_from: /rails-structured-logging/production/redis/host
        - name: REDIS_PORT
          value_from: /rails-structured-logging/production/redis/port

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets: ${SUBNETS}
      security_groups: ${SECURITY_GROUPS}
      assign_public_ip: DISABLED
  task_placement:
    strategy:
      - type: spread
        field: attribute:ecs.availability-zone
      - type: spread
        field: instanceId
