defaults: &defaults
  host: <%= ENV.fetch('MONGO_HOST') %>
  user: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
  auth_source: admin
  options:
    max_pool_size: 100
    ssl: false

development:
  <<: *defaults
  database: rails_mongo_mapper_development

test:
  <<: *defaults
  database: rails_mongo_mapper_test
  w: 0

# set these environment variables on your prod server
production:
  <<: *defaults
  database: rails_mongo_mapper
