---
version: '3.7'
services:
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    init: true
    ports:
      - 6379
    volumes:
      - redis:/data

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: dev
    init: true
    depends_on:
      - redis
    command: bash -c 'while :; do echo "running..."; sleep 10; done'
    environment:
      ADOBE_CLIENT_ID: ${ADOBE_CLIENT_ID}
      ADOBE_CLIENT_SECRET: ${ADOBE_CLIENT_SECRET}
    volumes:
      - .:/app
    ports:
      - 8080

  nginx:
    image: nginx:1.19
    init: true
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/templates
      - ./docker/nginx/certs:/etc/nginx/ssl
    ports:
      - 8000:8000

volumes:
  redis:
    driver: local
