apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template
spec:
  entrypoint: rake-task

  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

  arguments:
    parameters:
    - name: args

  templates:
  - name: rake-task
    inputs:
      parameters:
      - name: args
        value: "{{arguments.parameters.args}}"
    container:
      image: k8s-argo-workflow-rackup:latest
      imagePullPolicy: Never
      command: [rake]
      args: ["{{inputs.parameters.args}}"]
      env:
      - name: WORKDIR
        value: /data
      volumeMounts:
      - name: workdir
        mountPath: /data
    outputs:
      artifacts:
      - name: result
        path: /data
