base: &base
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  host: <%= ENV.fetch('DB_HOST'){ 'localhost' } %>
  port: <%= ENV.fetch('DB_PORT'){ '3306' } %>
  username: <%= ENV.fetch('DB_USER'){ 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD'){ '' } %>
  pool: 5
  timeout: 5000

development:
  <<: *base
  database: rails_structured_logging_development

test:
  <<: *base
  database: rails_structured_logging_test

production:
  <<: *base
  database: rails_structured_logging_production
