apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k-s-argo-workflow
build:
  artifacts:
  - image: k8s-argo-workflow-rackup
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
    - k8s/base
