---
version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: development
    init: true
    command:
      codep
        "1=bash -c 'while :; do echo test; sleep 10; done'"
    volumes:
      - .:/app
      - gomod:/go

volumes:
  redis:
    driver: local
  gomod:
    driver: local
