---
version: '3.7'
services:
  proxy:
    build:
      context: .
      dockerfile: docker/proxy/Dockerfile
    init: true
    command: go run proxy.go
    volumes:
      - .:/app
    ports:
      - ${DOCKER_HOST_PROXY_PORT}:8080

  proxy2:
    build:
      context: .
      dockerfile: docker/proxy/Dockerfile
    init: true
    command: go run proxy.go
    volumes:
      - .:/app
    ports:
      - 8080
    environment:
      SECONDARY: 1

  nginx:
    image: nginx
    init: true
    ports:
      - ${DOCKER_HOST_WEB_PORT}:80

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    init: true
    command: bash -c 'while :; do echo wait; sleep 60; done'
