---
version: '3.7'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
    extra_hosts:
      - host.docker.internal:host-gateway
