FROM nginx:latest

RUN apt-get update -qq && \ 
    apt-get install -y tree vim less curl dnsutils net-tools procps

ADD docker/nginx/nginx.conf /etc/nginx/nginx.conf
ADD docker/nginx/app.conf.prod /etc/nginx/conf.d/default.conf
