---
version: '3.7'
services:
  db:
    image: mysql:5.7
    init: true
    volumes:
      - db:/var/lib/mysql
      - ./docker/db:/etc/mysql/conf.d:ro
    ports:
      - ${DOCKER_HOST_DB_PORT:-3306}:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  redis:
    image: redis:5.0
    init: true
    ports:
      - ${DOCKER_HOST_REDIS_PORT:-6379}:6379
    command: redis-server --appendonly yes
    volumes:
      - redis:/data

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: base
    init: true
    command:
      prehook "0=rm -f tmp/pids/server.pid" --
      codep
        "1=rails s -p 3000 -b 0.0.0.0"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - ${DOCKER_HOST_APP_PORT:-3000}:3000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ''
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  db:
    driver: local
  redis:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
  cache:
    driver: local
