---
version: '3.5'
services:
  # @see https://hub.docker.com/_/mysql/
  db:
    build: docker/mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d:ro
    ports:
      - $DOCKER_HOST_DB_PORT:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  app:
    build: docker/rails
    command: /bin/bash -c "rm -rf tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    volumes:
      - .:/app:rw
      - cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    ports:
      - $DOCKER_HOST_APP_PORT:3000
    environment:
      DATABASE_HOST: db

  nginx:
    build: docker/nginx
    depends_on:
      - app
    ports:
      - $DOCKER_HOST_NGINX_PORT:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql_data:
    driver: local
  bundle:
    driver: local
  cache:
    driver: local
