---
services:
  app_base:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    init: true
    command: sleep infinity
    volumes:
      - type: bind
        source: ..
        target: /sandbox
      - type: volume
        source: cache
        target: /sandbox/rails-semantic-logger/tmp/cache
      - type: volume
        source: node_modules
        target: /sandbox/rails-semantic-logger/node_modules
      - type: volume
        source: bundle
        target: /usr/local/bundle
    environment:
      DB_HOST: db

  app:
    extends:
      service: app_base
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        rm -rf tmp/pids/server.pid &&
        bundle exec rails s -b 0.0.0.0 -p 3000
      "
    ports:
      - target: 3000
        published: ${DOCKER_HOST_APP_PORT:-3000}

  db:
    image: mysql:8
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    ports:
      - target: 3306
        published: ${DOCKER_HOST_DB_PORT:-3306}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 10s
      start_interval: 1s
      interval: 600s
      timeout: 20s
      retries: 0

volumes:
  mysql_data:
  bundle:
  node_modules:
  cache:
